### ISSUE TITLE
test reports

### ISSUE THREAD

**Issue by pieterlukasse** [thehyve/cbioportal-gsva-analysis#1]
Hi @dionnezaal , @sandertan ,

can we please add a `test_reports` folder folder here with the documents that contain all the tests we have done and documented. Think of @dionnezaal 's internship report and perhaps also @sandertan 's use cases document. Thanks!

**Comment by sandertan** [comment]
Sorry, haven't done this...

**Comment by pieterlukasse** [comment]
any updates?

**Comment by Sjoerd-van-Hagen** [comment]
We can close this.
